/*
* Author : Avnio
* Created Date : 4th January 2022
* Class Name : CreateProjectFromProjectHubTest
* Details : Test class for CreateProjectFromProjectHubController
* Modification Log: 
* Ver   Date          Author    Modification
* 1.0   04-01-2023    Avnio     Initial Version
*/

@isTest
public class CreateProjectFromProjectHubTest {
	static testMethod void init() {
        CreateProjectFromProjectHubController.getListOfRecordType();
    }
    
    
}