/*
* Author : Avnio
* Created Date : 4th January 2022
* Class Name : DTOProjectQuestionConfiguration
* Details : Wrapper class for project question configuration
* Modification Log: 
* Ver   Date          Author    Modification
* 1.0   04-01-2023    Avnio     Initial Version
*/

public class DTOProjectQuestionConfiguration {
    public String subcategoryCellAddress;
    public DTOProjectConfiguration.ReviewerConfig reviewerConfig;
    public List<String> QuestionReferencePaths;
    public String QuestionPath;
    public String pathname;
    public String pageURL;
    public List<DTOProjectConfiguration.Compliances> compliances;
    public String categoryCellAddress;
    public List<String> AnswerReferencePaths;
    public String AnswerPath;
}